# Generated by Django 5.2.9 on 2025-12-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idea", models.CharField(max_length=255)),
                ("result", models.TextField()),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("time_to_cash", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IncomeTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
