# Generated by Django 5.2.9 on 2025-12-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AI_Insight",
        ),
    ]
