# Generated by Django 5.2.9 on 2025-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_delete_ai_insight"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="margins",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="business",
            name="orders",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="business",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
